### PR TITLE
[WIP][VIZ] handle single definition across multiple files - SPM example

### PR DESCRIPTION
**Pull request by remiadon**
@cmaumet  here is the graph I get for SPM default, simply running
```bash
python bids_prov/visualize.py examples/spm_default/*.json -o spm_defautl.png
```

It's a large graph, maybe we can shorten names and identifiers for readability.

spm_defautl

### CODE REVIEW

**Comment by cmaumet** [comment]
Hi @remiadon! Great! It looks like a few links are missing (which might help with getting the schema a bit more vertical): for example `segment` activity has no `used` relationship? Or `anat unzipped` is not used by any activity?

**Comment by remiadon** [comment]
@cmaumet here is tthe graph I get now, running
```bash
python bids_prov/visualize.py examples/spm_default/*.json --omit-details -o spm_defautl.png
```
spm_defautl

I added an `--omit-details` flag, to skip optional fields and make the graph clearer

**Comment by cmaumet** [comment]
Discussed w/ @remiadon on Sept 22:
 - [ ] segment should use output of "updated anat nii header"
 - [ ] check all grey entities (undefined)

**Comment by remiadon** [comment]
@cmaumet I went on the W3C doc and searched for "qualified relationship"
According to [these graphs](https://www.w3.org/TR/prov-o/diagrams/qualified-patterns.svg), it seems that those relations won't help with simplifying the overall representation of our graph, as such relationship is modeled as an extra node

**Comment by remiadon** [comment]
@cmaumet I tried to represent the "edit file" operation using [prov:wasInfluencedBy](https://www.w3.org/TR/prov-o/#wasInfluencedBy). I get a graph with a single `SPM.mat` file

spm_default

**Comment by remiadon** [comment]
Note that this is the best looking graph I ever had, "raw"-labeled data sources are located at the top while produced outputs lie at the bottom

**Comment by remiadon** [comment]
@cmaumet can you comment on the graph above please ? If you are OK we'll have to add this in new_features.md

**Comment by cmaumet** [comment]
Thanks @remiadon! The graph looks great!!

Agreed on qualified relationship adding complexity to the graph...

I'm not sure about wasInfluencedBy, I'll have to double-check.

**Comment by cmaumet** [comment]
I'd say let's merge this PR and fix the remaining few things in a separate PR (that do not include the multi-file reading).

**Comment by remiadon** [comment]
@cmaumet OK for merging !! multi-file reading is already implemented in this PR ...

**Pull request merged**
