### PR TITLE
Fsl default

### PR DESCRIPTION
**Pull request by remiadon**
Delivery
- [X] pipeline as an image included
- [ ] JSON-ld example 
- [x] update `new_features.md` at the root of the project

### CODE REVIEW

**Comment by remiadon** [comment]
@cmaumet  there are many things to improve
First of all the current flow is a very high level view of what happened. FSL gives access to a "Log" interface, where every processing step is logged. Flow are decoupled into many calls to fsl binaries, with their respective arguments , eg : `/usr/share/fsl/5.0/bin/mainfeatreg -F 6.00 -d /data/fmri1/fluency_task/fmri.feat ...` . To stay as close as possible from this we can define Activities and "sub-avtivities"

```json
"prov:Activity : {
       preprocessing : [
          {
           "@id"  : ""
          }
       ]
   }"
```

**Comment by remiadon** [comment]
@cmaumet do you know a tool for json-ld visualisation ? other than json-ld playground I mean
Would make my life easier

**Comment by cmaumet** [comment]
Hi @remiadon! I've looked around pyld and rdflib-jsonld but did not find examples (though there must be). Have you looked at those libraries yet? --> https://json-ld.org/#developers

**Comment by remiadon** [comment]
@cmaumet when I run your notebook I get the following error
image

I don't understand this error
Any idea why ?

**Comment by remiadon** [comment]
I actually had the same while trying to visualize many jsonld files as a single graph on my machine

**Comment by cmaumet** [comment]
@remiadon - can you share which versions you have of all the libraries in `requirements.txt`. I don't have this error myself so maybe are setup are different.

**Comment by cmaumet** [comment]
And can you confirm that you do not have any pending changes (i.e. `git status` returns no changes to be commited)?

**Comment by remiadon** [comment]
@cmaumet can you run a `pip freeze` and copy/paste the result here ? to be sure

**Comment by remiadon** [comment]
> And can you confirm that you do not have any pending changes (i.e. `git status` returns no changes to be commited)?

Confirmed

**Comment by remiadon** [comment]
> @cmaumet can you run a `pip freeze` and copy/paste the result here ? to be sure

Or at least a 
```bash
pip freeze | grep rdf
```

which gives me
``` bash
rdflib==4.2.2
rdflib-jsonld==0.5.0
```

**Comment by cmaumet** [comment]
Will do! @remiadon - can you give the versions of all libraries in https://github.com/Inria-Visages/BIDS-prov/blob/fsl_default/requirements.txt

**Comment by cmaumet** [comment]
```
$ pip freeze | grep LD
PyLD==2.0.2
$ pip freeze | grep rdf
rdflib==5.0.0
rdflib-jsonld==0.5.0
$ pip freeze | grep prov
prov==1.5.3
$ pip freeze | grep graphviz
graphviz==0.14.1
$ pip freeze | grep click
click==7.1.2
```

**Comment by remiadon** [comment]
TODO 
Sub-divide "Stats" activity into "film_gls" and "smoothness" 
see [this log file](https://github.com/incf-nidash/nidmresults-examples/blob/master/fsl_default/logs/feat3_stats)

**Comment by remiadon** [comment]
@cmaumet I just double checked versions, I get the same error again and again when I try to run your notebook

**Comment by cmaumet** [comment]
Hi @remiadon! Oh no... :( Unfortunately I won't be able to look into this this afternoon.

Does the first part of the notebook work (i.e. the vizualisation computed using a very small example with only 2 objects)? If that's the case, you could try going step by step in adding objects towards re-creating the larger file until you pinpoint which part of the document creates that error?

**Comment by remiadon** [comment]
@cmaumet Yes the first part works like a charm

I'll try to do it step by step yes

**Comment by cmaumet** [comment]
@remiadon: can you check if it's better now?

**Comment by cmaumet** [comment]
@remiadon - this looks good to me! Let's merge this one and we can iterate on the FSL example in another PR/issue.

**Pull request merged**
