### PR TITLE
Add codespell workflow, config and fix some typos

### PR DESCRIPTION
**Pull request by yarikoptic**
One semantic change that instead of using `bloc` [*] I agreed with codespell to use `block` and thus also changed uses in the composite variables as well

[*]
```
  bloc
      n 1: a group of countries in special alliance [syn: {bloc},
           {axis}]
```

### CODE REVIEW

**Comment by cmaumet** [comment]
Thanks @yarikoptic! @bclenet: I think we can merge this one as well (and re-run the automated nidm example github action)

**Comment by yarikoptic** [comment]
it has been awhile... not sure why even .pngs were changed etc... needs to be updated anyways since conflicts now etc.  Will do now

**Comment by yarikoptic** [comment]
done now, please check/merge before new conflicts arise

**Comment by cmaumet** [comment]
Thanks @yarikoptic!

**Pull request merged**
