### PR TITLE
[WIP]v0 for spm parser

### PR DESCRIPTION
**Pull request by remiadon**
This PR tries to introduce a parser for SPM, i.e a piece of program that takes `.m` files as those available to SPM users and produces the corresponding BIDSprov graph, in jsonld

- [x] implement a v0
- [x] CI script to check conversion is OK with a few different datasets
- [x] bash example with visualization
- [x] add more examples

### CODE REVIEW

**Comment by remiadon** [comment]
@cmaumet Here is what I get when I run 
```python
python bids_prov/spm_parser.py examples/spm_default/batch.m -o test.json && python bids_prov/visualize.py test.json && open test.png```

![test](https://user-images.githubusercontent.com/2931080/107224069-3e7b6b80-6a17-11eb-83fd-47460e8bbb37.png)

**Comment by cmaumet** [comment]
Discussed w/ @remiadon  on Feb 8, next steps include:
 - Reverse dependencies into "used" instead of "wasGeneratedBy"
 - Add wasAssociatedWith relation between all activities and the SPM software
 - For each cfg_dep add a wasGeneratedBy relation between the entity and the corresponding activity
 - Try and use prov library

**Comment by remiadon** [comment]
Here is what I get after f09413687e1b6804039bebb8a510f3d400bced94

test

**Comment by remiadon** [comment]
And here is what I get now, after 46436ff

test

@cmaumet do you see anything abnormal ?

**Comment by cmaumet** [comment]
Thanks @remiadon! I did not see anything specific but in general I think all activities should have a "used" relationship and this does not seem to be the case in the graph above. Can you have a look?

**Comment by remiadon** [comment]
@cmaumet what I get after eeb94c8

test

It just took a bit more time to debug than what I expected :) 

Do you see any blocking item now ??

**Comment by remiadon** [comment]
Oh I see there is a buggy part : "file(1)_4" and "file(1)_3" should not be chained ...

**Comment by remiadon** [comment]
and here is what I get for the `explicit_mask`example https://github.com/incf-nidash/nidmresults-examples/tree/master/spm_explicit_mask

explicit_mask

**Review by cmaumet — COMMENTED** [review]
Hey @remiadon, thanks for this.

One quick note on your latest graph:
 - the links between the entities and the SPM software should be removed (to only retain the links between the activities and the software).

Once this is done, I am happy to merge this. For the next sprint, here are a few things we should look at to improve this example:
 - `file_move_2` has no wasGeneratedBy link. Do you think there could be a confusion with the output of file_move_1? 
 - in the name of the Activity could we keep everything after "spm.", for example "preproc._7" would become "spatial.preproc._7"
 - To make the graph easier to read, is there an option to hide identifiers?

**Comment by remiadon** [comment]
@cmaumet Thanks for reviewing

As introduced in 5f14a6c0d1453d98f949eb891c50880029c46ce6

Here is the generated graph
test

**Comment by remiadon** [comment]
And in 434eeaff0f78e0a7311184785b125b0790930379 I fixed activity names :) I still left a limit to 30 for activity names, otherwise I find it quite verbose
test

**Comment by cmaumet** [comment]
Ok let's merge and we'll keep the other items for the next iteration!

**Comment by remiadon** [comment]
@cmaumet I tried to fix what you mentionned about "file_move_2" by linking dependencies in another manner

Here is the graph I get 

test

I do think it's way better, what do you think ?

**Comment by cmaumet** [comment]
Yes! There is one remaining missing link :  "fmri_spec" used "Smoothed images"

**Comment by remiadon** [comment]
@cmaumet ready to merge

**Pull request merged**
