### PR TITLE
Update contributors list 38

### PR DESCRIPTION
**Pull request by cyril-data**
Hi @cmaumet 

This PR is up to be reviewed. 

except resolving merging conflict, the only change should be on the README

### CODE REVIEW

**Comment by thomasbtnfr** [comment]
For the contributors, everything seems good to me ! For the choice of icons for each contributor, I let @cmaumet answer.

Furthermore, it seems that there are other changes other than for the README. I don't know if it affects the generated jsonld. Maybe it deserves a comment.

**Comment by thomasbtnfr** [comment]
For the contributors, everything seems good to me ! For the choice of icons for each contributor, I let @cmaumet answer.

Furthermore, it seems that there are other changes other than for the README. I don't know if it affects the generated jsonld. Maybe it deserves a comment.

**Comment by thomasbtnfr** [comment]
So it's good for me !

**Comment by cmaumet** [comment]
Discussed on March 30th -- Camille to update with contributor roles

**Comment by cyril-data** [comment]
@cmaumet : you should have to add the missing contributions with respect to the following legend : https://allcontributors.org/docs/en/emoji-key

**Pull request merged**
